const state={students:[],faculty:[],lastWeek:[],thisWeek:[],view:'dashboard'};
const demoStudents=[['ENR-2401','Aarav Mehta',88,91,'Dr. Kavita Rao'],['ENR-2402','Diya Sharma',72,68,'Prof. Rohan Mehta'],['ENR-2403','Kabir Singh',79,84,'Dr. Kavita Rao'],['ENR-2404','Ananya Iyer',94,93,'Prof. Neha Kapoor'],['ENR-2405','Rohan Verma',64,59,'Prof. Rohan Mehta'],['ENR-2406','Meera Joshi',81,86,'Prof. Neha Kapoor'],['ENR-2407','Arjun Nair',73,77,'Dr. Kavita Rao'],['ENR-2408','Ishita Patel',91,90,'Prof. Rohan Mehta'],['ENR-2409','Vivaan Shah',69,62,'Prof. Neha Kapoor'],['ENR-2410','Saanvi Gupta',86,89,'']].map(([enrollment,name,attendance,last,mentor])=>({enrollment,name,attendance,last,mentor,remarks:''}));
const demoFaculty=[['Dr. Kavita Rao','kavita.rao@pica.edu'],['Prof. Rohan Mehta','rohan.mehta@pica.edu'],['Prof. Neha Kapoor','neha.kapoor@pica.edu']].map(([name,email])=>({name,email}));
function $(id){return document.getElementById(id)}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function initials(n){return (n||'?').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function normal(s){return String(s??'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function num(v){if(typeof v==='number')return v;const x=parseFloat(String(v??'').replace('%','').replace(',','.'));return isNaN(x)?null:x}
function detect(row,keys){for(const k of keys){const found=Object.keys(row).find(x=>normal(x).includes(k));if(found&&row[found]!==''&&row[found]!=null)return row[found]}return null}
function readWorkbook(file,callback){const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array',cellDates:true});let rows=[];wb.SheetNames.forEach(sn=>{const ws=wb.Sheets[sn];rows=rows.concat(XLSX.utils.sheet_to_json(ws,{defval:'',raw:false}));});callback(rows);showToast(`${file.name} imported successfully`)}catch(err){showToast('Could not read this file. Please check the format.')}};reader.readAsArrayBuffer(file)}
function parseStudents(rows){return rows.map(r=>{const enrollment=detect(r,['enrollment','enrolment','rollno','rollnumber','studentid','registration']);const name=detect(r,['studentname','name','student','learner']);const attendance=detect(r,['totalattendance','attendance','present','percentage','attend']);return {enrollment:String(enrollment??'').trim(),name:String(name??'').trim(),attendance:num(attendance)??0,last:num(detect(r,['lastweek','previous','prior']))??0,mentor:'',remarks:''}}).filter(x=>x.name||x.enrollment)}
function parseFaculty(rows){return rows.map(r=>({name:String(detect(r,['facultyname','mentorname','faculty','mentor','name'])??'').trim(),email:String(detect(r,['email','mail'])??'').trim()})).filter(x=>x.name)}
function render(){renderMetrics();renderChart();renderStudents();renderAllocation();renderFollowups();$('studentCount').textContent=state.students.length;$('allocationStudents').textContent=state.students.length;$('facultyCount').textContent=state.faculty.length;const assigned=state.students.filter(s=>s.mentor).length;$('assignedCount').innerHTML=`${assigned}<span class="muted-total"> / ${state.students.length}</span>`;$('unassignedCount').textContent=state.students.length-assigned;const progress=state.students.length?Math.round(assigned/state.students.length*100):0;$('allocationProgress').textContent=progress+'%';$('progressBar').style.width=progress+'%'}
function renderMetrics(){const a=state.students;const avg=a.length?Math.round(a.reduce((x,s)=>x+s.attendance,0)/a.length):0;const attention=a.filter(s=>s.attendance<75).length;const improved=a.filter(s=>s.attendance>s.last).length;const healthy=a.filter(s=>s.attendance>=75&&s.attendance>=s.last).length;$('avgAttendance').textContent=avg+'%';$('attentionCount').textContent=attention;$('weekChange').textContent=(a.length?Math.round((improved/a.length)*100):0)+'%';$('healthyNum').textContent=healthy;$('improvedNum').textContent=a.filter(s=>s.attendance>=75&&s.attendance<s.last).length;$('needsNum').textContent=attention;$('healthyPct').textContent=(a.length?Math.round(healthy/a.length*100):0)+'%';const h=a.length?healthy/a.length*360:0;const im=a.length?state.students.filter(s=>s.attendance>=75&&s.attendance<s.last).length/a.length*360:0;$('donut').style.background=`conic-gradient(var(--green) 0deg ${h}deg,var(--yellow) ${h}deg ${h+im}deg,#ed6b73 ${h+im}deg 360deg)`}
function renderChart(){const vals=state.students.length?[...Array(7)].map((_,i)=>Math.max(0,Math.min(100,Math.round(state.students.reduce((x,s)=>x+s.attendance,0)/state.students.length+(i-3)*1.5))):[0,0,0,0,0,0,0];$('chartBars').innerHTML=vals.map((v,i)=>`<div class="bar ${i===6?'today':''}" style="height:${v}%" data-value="${v}"></div>`).join('')}
function renderStudents(){const q=normal($('studentSearch').value);const filter=$('statusFilter').value;const rows=state.students.filter(s=>(!q||normal(s.name).includes(q)||normal(s.enrollment).includes(q))&&(filter==='all'||filter==='attention'&&s.attendance<75||filter==='unassigned'&&!s.mentor));$('tableCount').textContent=state.students.length+' students';$('studentTable').innerHTML=rows.map(s=>{const trend=s.attendance>s.last?'↑ Improved':s.attendance<s.last?'↓ Declined':'— Stable';const status=s.attendance<75?'attention':!s.mentor?'unassigned':s.attendance>s.last?'improved':'healthy';const label=status==='attention'?'Below 75%':status==='unassigned'?'Unassigned':status==='improved'?'Improved':'Healthy';return `<tr><td><div class="student-cell"><span class="student-avatar">${initials(s.name)}</span>${s.name||'Unnamed student'}</div></td><td>${s.enrollment||'—'}</td><td><span class="att-cell">${s.attendance}%</span><span class="att-bar"><i style="width:${Math.min(s.attendance,100)}%;background:${s.attendance<75?'var(--red)':'var(--green)'}"></i></span></td><td class="${trend[0]==='↓'?'red-text':'green-text'}">${trend}</td><td>${s.mentor||'<span class="muted-total">Not assigned</span>'}</td><td><span class="badge ${status}">${label}</span></td><td><button class="more-btn" onclick="editRemark('${s.enrollment}')">•••</button></td></tr>`}).join('');$('emptyState').style.display=state.students.length?'none':'block'}
function renderAllocation(){const q=normal($('allocationSearch').value);const rows=state.students.filter(s=>!q||normal(s.name).includes(q)||normal(s.enrollment).includes(q)||normal(s.mentor).includes(q));$('allocationTable').innerHTML=rows.map(s=>`<tr><td><b>${s.enrollment||'—'}</b></td><td>${s.name}</td><td>${s.attendance}%</td><td><select class="mentor-select" data-enrollment="${s.enrollment}"><option value="">Unassigned</option>${state.faculty.map(f=>`<option ${s.mentor===f.name?'selected':''}>${f.name}</option>`).join('')}</select></td><td><span class="badge ${s.mentor?'improved':'unassigned'}">${s.mentor?'Assigned':'Pending'}</span></td><td></td></tr>`).join('');document.querySelectorAll('.mentor-select').forEach(el=>el.onchange=()=>{const s=state.students.find(x=>x.enrollment===el.dataset.enrollment);if(s){s.mentor=el.value;render();showToast('Mentor assignment saved')}});$('allocationEmpty').style.display=state.students.length?'none':'block'}
function getFollowups(){return state.students.map(s=>({s,last:s.last||s.attendance,now:s.attendance,change:s.attendance-(s.last||s.attendance)}))}
function renderFollowups(){const rows=getFollowups();const mentors=[...new Set(state.students.map(s=>s.mentor).filter(Boolean))];$('mentorFilter').innerHTML='<option value="all">All mentors</option>'+mentors.map(m=>`<option>${m}</option>`).join('');const mf=$('mentorFilter').value,pf=$('priorityFilter').value;const filtered=rows.filter(x=>(mf==='all'||x.s.mentor===mf)&&(pf==='all'||pf==='high'&&x.change<0||pf==='medium'&&x.change>=0));$('followupTable').innerHTML=filtered.map(x=>{const priority=x.now<75||x.change<=-5?'high':x.change<0?'medium':'low';const label=priority==='high'?'High priority':priority==='medium'?'Monitor':'On track';return `<tr><td><div class="student-cell"><span class="student-avatar">${initials(x.s.name)}</span>${x.s.name}</div></td><td>${x.s.mentor||'Unassigned'}</td><td>${x.last}%</td><td>${x.now}%</td><td class="${x.change<0?'red-text':'green-text'}"><b>${x.change>0?'+':''}${x.change}%</b></td><td><span class="priority ${priority}">● ${label}</span></td><td>${x.s.remarks|| (priority==='high'?'Discuss attendance drop':'Keep monitoring')}</td></tr>`}).join('');$('followupEmpty').style.display=state.students.length?'none':'block';const needs=rows.filter(x=>x.now<75||x.change<0).length;$('reviewedCount').textContent=rows.length;$('followImproved').textContent=rows.filter(x=>x.change>0).length;$('followAttention').textContent=needs;$('avgChange').textContent=(rows.length?rows.reduce((a,x)=>a+x.change,0)/rows.length:0).toFixed(1)+'%'}
function exportCsv(rows,name){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.csv';a.click();showToast('Editable Excel-compatible export downloaded')}
function exportData(mode){if(mode==='follow'){exportCsv([['Student name','Enrollment number','Mentor','Last week','This week','Change','Priority'],...getFollowups().map(x=>[x.s.name,x.s.enrollment,x.s.mentor,x.last,x.now,x.change,x.now<75||x.change<0?'High':'On track'])],'pica-follow-up')}else exportCsv([['Student name','Enrollment number','Total attendance','Mentor','Status'],...state.students.map(s=>[s.name,s.enrollment,s.attendance,s.mentor,s.attendance<75?'Below 75%':'Healthy'])],'pica-attendance')}
function exportPdf(){if(!state.students.length)return showToast('Add attendance data before exporting');const {jsPDF}=window.jspdf;const doc=new jsPDF();doc.setFontSize(20);doc.text('PICA · Student Attendance Report',15,18);doc.setFontSize(9);doc.text(new Date().toLocaleDateString(),15,25);let y=38;doc.setFontSize(10);doc.text('Student',15,y);doc.text('Enrollment',80,y);doc.text('Attendance',130,y);doc.text('Mentor',165,y);y+=8;state.students.forEach(s=>{doc.text(String(s.name).slice(0,30),15,y);doc.text(String(s.enrollment),80,y);doc.text(String(s.attendance)+'%',130,y);doc.text(String(s.mentor||'Unassigned').slice(0,25),165,y);y+=7;if(y>280){doc.addPage();y=20}});doc.save('pica-attendance-report.pdf');showToast('PDF report downloaded')}
function useDemo(){state.students=demoStudents.map(x=>({...x}));state.faculty=demoFaculty.map(x=>({...x}));render();showToast('Demo workspace loaded')}
function editRemark(enrollment){const s=state.students.find(x=>x.enrollment===enrollment);const r=prompt('Add a remark for '+s.name,s.remarks||'');if(r!==null){s.remarks=r;render()}}
function switchView(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===view));const labels={dashboard:'Dashboard',allocation:'Mentor allocation',followups:'Mentor follow-up'};$('crumbCurrent').textContent=labels[view]}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('demoData').onclick=useDemo;$('attendanceFile').onchange=e=>e.target.files[0]&&readWorkbook(e.target.files[0],rows=>{state.students=parseStudents(rows);render()});$('facultyFile').onchange=e=>e.target.files[0]&&readWorkbook(e.target.files[0],rows=>{state.faculty=parseFaculty(rows);$('facultyStatus').textContent=`${state.faculty.length} mentors found`;render()});$('lastWeekFile').onchange=e=>e.target.files[0]&&readWorkbook(e.target.files[0],rows=>{state.lastWeek=parseStudents(rows);$('lastWeekStatus').textContent=`${state.lastWeek.length} students found`;state.lastWeek.forEach(x=>{const s=state.students.find(s=>s.enrollment===x.enrollment||s.name===x.name);if(s)s.last=x.attendance});render()});$('thisWeekFile').onchange=e=>e.target.files[0]&&readWorkbook(e.target.files[0],rows=>{state.thisWeek=parseStudents(rows);$('thisWeekStatus').textContent=`${state.thisWeek.length} students found`;state.thisWeek.forEach(x=>{const s=state.students.find(s=>s.enrollment===x.enrollment||s.name===x.name);if(s)s.attendance=x.attendance});render()});$('autoAssign').onclick=()=>{if(!state.faculty.length)return showToast('Import faculty details first');state.students.forEach((s,i)=>s.mentor=state.faculty[i%state.faculty.length].name);render();showToast('Mentors distributed equally')};$('studentSearch').oninput=renderStudents;$('statusFilter').onchange=renderStudents;$('allocationSearch').oninput=renderAllocation;$('mentorFilter').onchange=renderFollowups;$('priorityFilter').onchange=renderFollowups;$('dashboardExport').onclick=()=>exportData('dashboard');$('allocationExport').onclick=()=>exportData('dashboard');$('followupExport').onclick=()=>exportData('follow');$('exportPdf').onclick=exportPdf;$('followupPdf').onclick=exportPdf;$('compareBtn').onclick=()=>{if(!state.lastWeek.length||!state.thisWeek.length)return showToast('Upload both attendance files first');renderFollowups();showToast('Attendance comparison generated')};$('templateBtn').onclick=()=>$('guideModal').classList.add('show');$('closeModal').onclick=$('closeGuide').onclick=()=>$('guideModal').classList.remove('show');render();
